### ISSUE TITLE
any plan to support brush?

### ISSUE THREAD

**Issue by wulucxy** [williaster/data-ui#106]
@williaster I have one case of great mount of data to show,  it's not possible to show all the data in the chart, and may be brushChart is a solution。

so， do you have any plan to support the brush chart?

thanks for the great work done for visualization。

**Comment by schicks** [comment]
@williaster I would be a big fan of brush support to allow more flexible histograms and timeseries charts. Is it a matter of needing support from vx?

**Comment by williaster** [comment]
hey @wulucxy and @schicks! 

yes, I agree and would love to get brush into the `histogram` + `xy-chart` packages as soon as it's added to vx. `@vx/brush` is expected to be added for v1 of `vx`, which is in the works now and hopefully will land in the next month or so. The API for interactions wasn't trivial which is why it has been delayed a bit (in addition to being busy with work projects).

**Comment by schicks** [comment]
That's really good to hear! both this and vx look like great projects; something that could actually fill d3's niche within the react ecosystem.

**Comment by williaster** [comment]
@wulucxy @schicks this should be coming in the next week or two 👍 cc @conglei

**Comment by conglei** [comment]
@wulucxy and @schick, I’ve opened a PR for the brushing functions FYI.

https://github.com/williaster/data-ui/pull/117

Any suggestion is welcome !

**Comment by wulucxy** [comment]
@conglei It's great。

I have one question，the common solution is like brush under the chart，like what echarts did:

```
http://echarts.baidu.com/examples/editor.html?c=candlestick-brush
```

so，why do you choose another way，what is the benefit of your try?

**Comment by conglei** [comment]
This feature has been implemented in  https://github.com/williaster/data-ui/pull/117.

**Comment by wulucxy** [comment]
@conglei how can I zoom the selection? like I want only show the period of my last selection?

**Comment by williaster** [comment]
@wulucxy you can see an example of this in [this](https://github.com/williaster/data-ui/pull/126) PR (not live in storybook yet)
