### ISSUE TITLE
XY-chart is not working correctly when passing time-series data

### ISSUE THREAD

**Issue by spa888** [williaster/data-ui#108]
I'm building the AreaSeries - band chart using data-ui/xy-chart.

I've passed the data:
[
  { x: new Date(), y: 10, y0: 5, y1: 15},
  ...
]

and xScale={{ type: 'time' }}

But the x-axis values are not generated correctly in xy-chart.
It seems that they only catch the value of date, like the format "YYYYMMDD" and ignore the time value.

Please check the issue and let me know the solution

**Comment by williaster** [comment]
Hey @spa888 thanks for checking out data-ui! Can you link to a more specific example demonstrating the issue?

[Here's a code sandbox](https://codesandbox.io/s/ypk9369xz9) I made that demonstrates how you can format an x-axis with hours instead of days.

**Comment by williaster** [comment]
Hi @spa888, any update on this?

**Comment by williaster** [comment]
going to close this, let me know if you're still having an issue.
