### ISSUE TITLE
Existing project integration

### ISSUE THREAD

**Issue by si-harps** [williaster/data-ui#116]
Hi, great library! I was wondering what would be the recommended way to integrate the components into an existing project?

**Comment by williaster** [comment]
Hi @si-harps, thanks for checking out `@data-ui`. It's a react-based library, which assumes you'd have a standard react webapp / package set up. After that you can add the relevant dependency as needed and simply import the components you need. 

```javascript
npm install --save @data-ui/xy-chart
```

For code snippet examples either look at the readmes, or check out the [example](https://github.com/williaster/data-ui/blob/master/packages/demo/examples/01-xy-chart/index.jsx) code.

**Comment by si-harps** [comment]
@williaster great, thanks for the quick response
