### ISSUE TITLE
Histogram renders incorrectly if the data is entirely zeroes and ones

### ISSUE THREAD

**Issue by kaiyoma** [williaster/data-ui#118]
This might actually be a more general issue of calculating the domain, but I'll leave the problem statement more specific for now.

Here's a sandbox: https://codesandbox.io/s/3rqvwxo42p

Two issues:

1. The second bin (the one containing all the ones) is missing entirely.
2. The density for the first bin is calculated incorrectly, as can be seen in the height of the bar and the value in the tooltip.

**Comment by williaster** [comment]
Hey @kaiyoma, thanks for raising this issue. 

This is definitely a bug, and related to #100. Will have a fix out shortly. Basically I was trimming the last bin for numeric unbinned data, which led to both errors you're seeing.

**Comment by williaster** [comment]
Fixed by #119

**Comment by williaster** [comment]
should be fixed in `@data-ui/histogram@^0.0.63`
