### ISSUE TITLE
Dual Line / Bar Series

### ISSUE THREAD

**Issue by si-harps** [williaster/data-ui#139]
@williaster - was wondering if something like this is possible right now?

http://bl.ocks.org/d3noob/e34791a32a54e015f57d

**Comment by williaster** [comment]
hey @si-harps thanks for checking out @data-ui! I'm going to close this as it duplicates #134. There is no native support for this, but there's a workaround with [code example here in #134](https://github.com/williaster/data-ui/issues/134#issuecomment-422653266).
