### ISSUE TITLE
Brush

### ISSUE THREAD

**Issue by kennetpostigo** [williaster/data-ui#160]
I was attempting to bring `<Brush />` into a dashboard i'm working on that uses `vx`, however I wasn't able to do so successfully. Is there any recommendations on how to do so or can you spot what I may be doing wrong here:
```js
<Brush
  width={props.width}
  height={props.height}
  top={0}
  left={0}
  xScale={xScale}
  yScale={yScale}
  handleSize={4}
  resizeTriggerAreas={["left", "right", "top", "bottom"]}
  brushDirection={"both"}
  onChange={handleBrushChange}
  onBrushEnd={d => {
    console.log("D:", d);
    return d;
  }}
  xAxisOrientation="left"
  yAxisOrientation="bottom"
  brushRegion={"chart"}
  selectedBoxStyle={{
    fill: "url(#brush_pattern)",
    stroke: "#DDD"
  }}
  ref={brush}
/>
```

The problem I would run into is that the component would render, but if I pan I can't see the selected area, however I do see the crosshairs from the component. I'm not quite sure what I'm doing wrong here. Our visualization is a Gantt that has a bunch of implementations details that is more difficult to rework but here is an example codepen from one of the `vx` examples that I made to show whats going on:
https://codesandbox.io/s/7m10yk3251

**Comment by williaster** [comment]
hmm, this wasn't implemented to work outside of `xy-chart` yet, @conglei would you expect this to be possible?

the ultimate goal is to move it to `@vx` as part of getting to v1, which is being tracked by #124. I hope that happens soon, PRs to help are totally welcome tho 😄

**Comment by kennetpostigo** [comment]
@williaster @conglei Do you know what XYChart provides that allows it to work?

**Comment by conglei** [comment]
Hi @kennetpostigo , currently Brush is only part of xy-chart as @williaster said. For more details, you can checkout the source code. https://github.com/williaster/data-ui/blob/master/packages/xy-chart/src/chart/XYChart.jsx. Here, you can see that there are some logic to bind eventlisteners etc. 

Our goal is to move it to @vx, and I will take a deep look to see how to make the demo in sandbox work.

**Comment by kennetpostigo** [comment]
Thanks @conglei
