### ISSUE TITLE
Set minimum bar length for BarSeries

### ISSUE THREAD

**Issue by gnijuohz** [williaster/data-ui#164]
When there is one large data point in the bar series, all the other bars would be reduced to nothing. In that case it's impossible to hover over them to show tooltips or click on the bars.

Is it possible to set a minimum bar length for the BarSeries (maybe via adding a minBarLength prop)?

**Comment by williaster** [comment]
Hi @gnijuohz thanks for checking out `@data-ui`. Do you have a code example you can link to? (easier to debug). 

Setting a minimum bar height seems like it could be a bit misleading depending on how large you set it, but you should be able to define this with the `scale` `range` attribute (e.g., `yScale={{ type: 'linear', range: [visHeight, minBarHeight] }}`. This config maps almost directly to `d3` scales which you can read more about [here](https://github.com/d3/d3-scale#linear-scales).

**Comment by gnijuohz** [comment]
@williaster Ah I think `yScale` will do! Will try that out. 

`@data-ui` is neat! thanks for your great work!

**Comment by williaster** [comment]
awesome! closing for now 👍
