### ISSUE TITLE
console error when clicking on bars in Firefox

### ISSUE THREAD

**Issue by gnijuohz** [williaster/data-ui#167]
To reproduce, open [this link](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=BarSeries%20--%20no%20axes&full=0&addons=0&stories=1&panelRight=0) in Firefox, open developer tools and click on the bars.

The following error will appear:

`TypeError: Value being assigned to SVGPoint.x is not a finite floating-point value`.

Chrome doesn't report this error.

Seems it's due to the fact that when the focus event is fired, clientX and clientY are both undefined: https://github.com/hshoff/vx/blob/master/packages/vx-event/src/localPoint.js#L32.

**Comment by williaster** [comment]
thanks for reporting this @gnijuohz ! Just getting back from PTO but will try to fix this soon 👍 PRs welcome if you'd like it sooner!

**Comment by williaster** [comment]
Should be [fixed in `0.0.77`](https://github.com/williaster/data-ui/blob/master/CHANGELOG.md#v0077)
