### ISSUE TITLE
How to make lines straight

### ISSUE THREAD

**Issue by lonalee** [williaster/data-ui#178]
Hello there.
I was astonished by all your brilliant data-ui!
I finally got a chart on my project to work just fine!
But only one thing is bothering me.
I wanna get the straight lines (using LineSeries with only curve lines)!
It would be great if you let me know how to handle the shape of lines.
Thank you very much.

**Comment by williaster** [comment]
Hi @lonalee I assume you are talking about the `@data-ui/xy-chart` package, you can accomplish this simply by setting the [`interpolation` prop](https://github.com/williaster/data-ui/blob/master/packages/xy-chart/src/series/LineSeries.jsx#L27) to `linear`. 

thanks for checking out `@data-ui`!
