### ISSUE TITLE
Extra svg text that causes scrollbar to appear on <body>

### ISSUE THREAD

**Issue by bluekvirus** [williaster/data-ui#180]
https://github.com/williaster/data-ui/blob/c30330ad2f57a1ba853ad17876c8538eacc51db4/packages/xy-chart/package.json#L38

The `@vx/text` util function is fixed but here we might want to reference `@vx/xy-chart: ^0.0.175` to pick up the fix from `@vx/text` 0.0.175 and above.

Thanks!

**Comment by williaster** [comment]
@bluekvirus this should now be fixed in `@data-ui/xy-chart@0.0.79`

**Comment by bluekvirus** [comment]
Awesome! Thanks :))
