### ISSUE TITLE
histogram tickLabelProps

### ISSUE THREAD

**Issue by mfe5003** [williaster/data-ui#183]
Hi, thanks making this library!

I am having an issue trying to pass tickLabelProps into a histogram XAxis.
When I do pass in a custom tickLabelProps function I get the following error:

VM538 1.chunk.js:894 Uncaught TypeError: Cannot read property 'bottom' of undefined

I believe I've tracked it down to the fix from commit 3a594deca588dd7761957f54de31177f09bed830 not being applied to the histogram axes.

I am having trouble confirming this locally since I am not familiar with installing local npm packages, but I believe simply applying the same fix as in packages/xy-chart/src/axis/XAxis.jsx should fix the issue.

Thanks

**Comment by williaster** [comment]
@mfe5003 this should be fixed in the [`0.0.80` release](https://github.com/williaster/data-ui/blob/master/CHANGELOG.md#v0080)
