### ISSUE TITLE
Histogram multiple series offset

### ISSUE THREAD

**Issue by philipgriggs** [williaster/data-ui#187]
Is it possible to offset the x-location and width when there are two `BarSeries`? Like the below image. 
![double_series](https://user-images.githubusercontent.com/38210431/64611144-b2e85000-d3c8-11e9-97cf-29f00151dec5.png)

**Comment by williaster** [comment]
Hi @philipgriggs, thanks for checking out `@data-ui`. Currently this is not possible with the `@data-ui/histogram` package, Bar series can only be overlaid on one another.

You can however do this with the `@data-ui/xy-chart` `GroupedBarSeries`, you'd just need to compute do the histogram binning yourself. See [this example](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=GroupedBarSeries).

Going to close this for now but happy to look at a PR if you are interested in adding this functionality!
