### ISSUE TITLE
How to set XYchart yAxis rangepadding

### ISSUE THREAD

**Issue by mcassels** [williaster/data-ui#189]
Hi, is there a way to set the rangePadding of the yAxis in an XYchart? I saw that XYchart sets the xAxis rangePadding to xScale.offset, but the yAxis rangePadding to null.

I want to create space at the top of the chart above the highest data point (i.e. want the yAxis to extend somewhat above the data range). Thanks!

**Comment by williaster** [comment]
👋  @mcassels, thanks for checking out `@data-ui`. Looks like you're correct that we [override `rangePadding` to `null`](https://github.com/williaster/data-ui/blob/07fcfe33c814023b7db085b2539192e93a92e52e/packages/xy-chart/src/chart/XYChart.jsx#L366) which I'd consider a 🐛.

I pushed a quick fix in #190 , as a temporary work around until I can release a new version (next few days) you could explicitly define the desired `domain` in `XYChart.props.yScale` object with the desired extra padding. This will be annoying if you don't already know the extent of data but might be better than nothing.

**Comment by mcassels** [comment]
Great, thank you!!

**Comment by williaster** [comment]
this should be fixed in `@data-ui/xy-chart@0.0.81`
