### ISSUE TITLE
Update visualizations

### ISSUE THREAD

**Issue by klinkow** [williaster/data-ui#206]
The npm package `data-ui` is no longer being maintained and should be upgraded to [visx](https://github.com/airbnb/visx). This will affect components:

`Summary/Histogram`
`Summary/ResponsiveHistogram`
`Summary/RadialChart`

and possibly others in the `javascript/src/components/Summarize` directory.

**Comment by williaster** [comment]
Hey @klinkow did you mean to open this in this repo?

**Comment by klinkow** [comment]
omg sorry, wrong repo. Thank you for all of your work on data-ui and visx! Closing... 😃
