### ISSUE TITLE
Update to React 16 and Enzyme 3

### ISSUE THREAD

**Issue by iancmyers** [williaster/data-ui#57]
React 16 and Enzyme 3 have been released and VX has been updated to support React 16. It would be great for data-ui to support React 16 as well.

**Comment by williaster** [comment]
thanks @iancmyers, absolutely, this is high on my todo list 👍 I should be able to prioritize it within the next week and will update this issue accordingly.

**Comment by iancmyers** [comment]
@williaster Thanks so much!
