### ISSUE TITLE
Question about data format of eventflow

### ISSUE THREAD

**Issue by hurcy** [williaster/data-ui#98]
Hi,
I think event flow is very interesting, so I want to test event flow using my dataset.
I checked format of sampleEvents of eventflow demo, and I created my example like as follows.
But the flows are not grouped like sampleEvents.
Could you give me advice?

```
{"allEvents" : [{
	"EVENT_ID": "user0",
	"EVENT_NAME": "I10",
	"TS": "2016-01-06 00:00:00"
}, {
	"EVENT_ID": "user0",
	"EVENT_NAME": "I10",
	"TS": "2016-01-26 00:00:00"
}, {
	"EVENT_ID": "user0",
	"EVENT_NAME": "K05",
	"TS": "2016-01-28 00:00:00"
}, {
	"EVENT_ID": "user0",
	"EVENT_NAME": "I69",
	"TS": "2016-01-28 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "I10",
	"TS": "2016-01-07 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "K05",
	"TS": "2016-02-02 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "I10",
	"TS": "2016-02-26 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "I10",
	"TS": "2016-05-04 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "K05",
	"TS": "2016-05-18 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "I10",
	"TS": "2016-07-06 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "F00",
	"TS": "2016-07-12 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "F00",
	"TS": "2016-08-03 00:00:00"
}, {
	"EVENT_ID": "user2",
	"EVENT_NAME": "F00",
	"TS": "2016-09-06 00:00:00"
}]
}
```

**Comment by williaster** [comment]
Hi @hurcy :wave:, thanks for checking out event-flow :) This looks okay to me except you may need to parse the `ts` strings into actual `Date`s as is done in [`sampleEvents`](https://github.com/williaster/data-ui/blob/4fc8b5fc3d1e29c4c108688f81db2d67e65ccfa0/packages/event-flow/src/fixtures/sampleEvents.js). 

If that doesn't work, could you create a minimal example to reproduce on a codesandbox for easier debugging?

**Comment by hurcy** [comment]
I could only reproduce my example like this.
https://codesandbox.io/s/xppzq41nwz
In event-flow demo, I switched from original example into my example.

2018-04-17 7:27 GMT+09:00 Chris Williams <notifications@github.com>:

**Comment by williaster** [comment]
[Here's a codesandbox ](https://codesandbox.io/s/x2myk0vkj4) that works with your data, the issue was parsing the date as I suspected.
